# Generated by Django 4.0.3 on 2022-03-30 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_posts_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='img',
        ),
    ]
